server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          # Client registration starts here
          oidc-client-2:
            # Our oidc-client needs a provider. The provider information has been registered
            # at the bottom of this configuration
            # The following client-id and client-secred will be sent to the authorization server
            # for client_credentials authentication to the authorization server. We don't need to
            # mention the client_credentials in the grant type here. Note that, here the client-secret
            # must not have {noop} or any other encoding type mentioned.
            client-id: oidc-client-2
            client-secret: "abc1234"
            # Our authorization grant type is authorization_code
            authorization-grant-type: authorization_code
            # The following redirect URL is the redirect URL definition of our client Server application.
            # It is generally the current application host address. The authorization server's redirect URL
            # definition means that this URL will be triggered when auth server redirects data to here.
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirect-uri: "http://resource-server-2:8082/{action}/oauth2/code/{registrationId}"
            # Scopes that will be displayed for requesting in the consent page.
            # Authorization server must have equal or more scopes than these in number
            scope:
              - openid
              - client-2
            client-authentication-method: client_secret_basic
            # This client name will display in the login screen as social login type
        # As mentioned above about provider, here we register the provider details
        # for any unknown provider with their issuer URI
        provider:
          oidc-client-2:
            issuer-uri: http://auth-server:8080

      # Since our application acts as both authorization client and resource server,
      # here is the configuration for resource server
      resource-server:
        jwt:
          issuer-uri: http://auth-server:8080