spring:
  security:
    user:
      # Definition of the user details that we will use for login
      # in the authorization server
      name: user
      password: "{noop}password"
    #      roles: USER,client-1
    # Oauth2 client registration starts from here
    oauth2:
      authorization-server:
        client:
          oidc-client-1:
            registration:
              client-id: oidc-client-1
              # 一般需要加密，POC暫時不加
              client-secret: "{noop}abc123"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              client-authentication-methods:
                - client_secret_basic
              # This following redirect URI will be used to redirect the resource owner to the
              # Client application after the resource owner (user) provides necessary consents.
              redirect-uris:
                - http://resource-server-1:8081/login/oauth2/code/oidc-client-1
                - http://resource-server-1:8081/authorized
              post-logout-redirect-uris:
                - http://resource-server-1:8081/
              # The scopes are defined in the authorization server.
              # These won't display in the consent page
              scopes:
                - openid
                - client-1
            # PKCE setting
            require-proof-key: true
            # Marking this flag as true will display the consent page
            require-authorization-consent: false
            # Here we set the access token and refresh token validity duration
            # in seconds
            token:
              access-token-time-to-live: 60s
              refresh-token-time-to-live: 120s
          oidc-client-2:
            registration:
              client-id: oidc-client-2
              # 一般需要加密，POC暫時不加
              client-secret: "{noop}abc1234"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              client-authentication-methods:
                - client_secret_basic
              # This following redirect URI will be used to redirect the resource owner to the
              # Client application after the resource owner (user) provides necessary consents.
              redirect-uris:
                - http://resource-server-2:8082/login/oauth2/code/oidc-client-2
                - http://resource-server-2:8082/authorized
              post-logout-redirect-uris:
                - http://resource-server-2:8082/
              # The scopes are defined in the authorization server.
              # These won't display in the consent page
              scopes:
                - openid
                - client-2
            # PKCE setting
            require-proof-key: true
            # Marking this flag as true will display the consent page
            require-authorization-consent: false
            # Here we set the access token and refresh token validity duration
            # in seconds
            token:
              access-token-time-to-live: 60s
              refresh-token-time-to-live: 120s
logging:
  level:
    org:
      springframework:
        security: trace